/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/neural_network.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Sphere008" geometry={nodes.Sphere008.geometry} material={nodes.Sphere008.material} position={[-8.07, -0.99, 5.82]} />
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[-0.01, -0.35, 0.02]} />
        <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={nodes.Sphere001.material} position={[7.13, -0.35, 0.02]} />
        <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={nodes.Sphere002.material} position={[-6.99, -0.35, 0.02]} />
        <mesh name="Sphere003" geometry={nodes.Sphere003.geometry} material={nodes.Sphere003.material} position={[-7.07, -0.35, -7.16]} />
        <mesh name="Sphere004" geometry={nodes.Sphere004.geometry} material={nodes.Sphere004.material} position={[-0.01, -0.35, -7.2]} />
        <mesh name="Sphere005" geometry={nodes.Sphere005.geometry} material={nodes.Sphere005.material} position={[6.92, -0.35, -7.12]} />
        <mesh name="Sphere006" geometry={nodes.Sphere006.geometry} material={nodes.Sphere006.material} position={[-7.07, -0.35, -14.05]} />
        <mesh name="Sphere007" geometry={nodes.Sphere007.geometry} material={nodes.Sphere007.material} position={[-0.01, -0.35, -14.09]} />
        <mesh name="Sphere009" geometry={nodes.Sphere009.geometry} material={nodes.Sphere009.material} position={[6.92, -0.35, -14.01]} />
      </group>
    </group>
  )
}

useGLTF.preload('/neural_network.glb')
